/*THIS CLASS AND ITS PACKAGE ARE AUTOGENERATED DURING BUILD/
/*****************ANY EDITS WILL BE LOST!!!****************/
package version;
public final class Version {
    public static final String PROJECT_NAME = "GuiCerberusV2";
    public static final String VERSION = "2.0.0-SNAPSHOT";
    public static final String PROJECT_NAME_VERSION = "GuiCerberusV2-2.0.0-SNAPSHOT-${SVN_REVISION}";
    public static final String BUILD_TIME = "20130626-1453";
    public static final String SVN_REVISION = "${SVN_REVISION}";
    private Version() {
        //empty and commented construcotr to comply with Sonar rules
    }
}
