=== Introduction

Cerberus has integrated a hook mecanism management.
That allow to react on some event in order to trigger asynchroniously some external notification or synchronize external systems (for reporting or test referencial).
On top of the public API available, that feature allow a better, easier and faster integration of Cerberus with external tools.
In stead of calling the API to get the data from Cerberus, you can ask Cerberus to call an external system once the corresponding Cerberus event occurs. No more periodic refresh of the systems, just push the data from Cerberus directly when necessary.

For that purpose for every event, you can link 0 to many connectors with the following parameters associated :

- *Object1 and Object2* are used to filter the hook trigger before trigerring it. Those values depend on the event reference.
- *Hook recipient* correspond to the recipent of the connector. It can be a URL or list of email depending on the connector.
- *Hook channel* correspond to the channel recipent of the connector. It is most of the time optional as not used by many connectors.
- *Active* boolean in order to temporary disable the hook
- *General description* of the hook

=== Events Referencial

9 events are available to be plugged :

- *CAMPAIGN_START*

 Occurs when a campaign is triggered. 
 
*[blue]#Object1#* : Filter the name of the campaign [optional]
 
- *CAMPAIGN_END*

 Occurs when a campaign ends. That event happened whatever the result of the campaign is.  

*[blue]#Object1#* : Filter the name of the campaign [optional]

- *CAMPAIGN_END_CIKO*

 Occurs when a campaign ends with a CI Score higher that threshold. In other word, that happens only when the global result of the campaign is KO. 

*[blue]#Object1#* : Filter the name of the campaign [optional]

- *EXECUTION_START*

 Occurs when a single Testcase execution is triggered.  
 
*[blue]#Object1#* : Filter the Test Folder [optional]

*[blue]#Object2#* : Filter the Testcase ID [optional]

- *EXECUTION_END*

 Occurs when a single Testcase execution ends. That event happened whatever the result of the execution is.
 
*[blue]#Object1#* : Filter the Test Folder [optional]

*[blue]#Object2#* : Filter the Testcase ID [optional]

- *EXECUTION_END_LASTRETRY*

 Occurs when a single Testcase execution ends during its last attempt (when retry feature is activated). That event happened whatever the result of the execution is.
 That event is only and always triggered once for every testcase execution that has been submited.

*[blue]#Object1#* : Filter the Test Folder [optional]

*[blue]#Object2#* : Filter the Testcase ID [optional]

- *TESTCASE_CREATE*

 Occurs when a Testcase has been created.  
 
*[blue]#Object1#* : Filter the Test Folder [optional]

*[blue]#Object2#* : Filter the Testcase ID [optional]

- *TESTCASE_UPDATE*

 Occurs when a Testcase has been updated.

*[blue]#Object1#* : Filter the Test Folder [optional]

*[blue]#Object2#* : Filter the Testcase ID [optional]

- *TESTCASE_DELETE*

 Occurs when a Testcase has been deleted. 

*[blue]#Object1#* : Filter the Test Folder [optional]

*[blue]#Object2#* : Filter the Testcase ID [optional]

=== Connectors

5 Connectors are available

- *SLACK*

 Generate a Slack notification.  
 
*[blue]#Hook Recipient#* : Webhook URL to Slack platform.

*[blue]#Hook Channel#* : Channel where the message will be sent. [optional]

- *GOOGLE-CHAT*

 Generate a notification to Google Chat platform.
 
*[blue]#Hook Recipient#* : Webhook URL to Google Chat platform.

- *TEAMS*

 Generate a notification to Microsoft Teams platform.
 
*[blue]#Hook Recipient#* : Webhook URL to Microsoft Teams platform.

- *EMAIL*

 Sends an email to a recipient list.
 
*[blue]#Hook Recipient#* : List of emails seperated by ;.

.Example
====
Paul SMITH <p.smith@mail.com> ; Marc DURANT <m.durant@mail.com> ; toto@newemail.com
====

- *GENERIC*

 Sends a native Cerberus JSON format message to a given URL.
 
*[blue]#Hook Recipient#* : Webhook URL to send the native Cerberus data structure.

