#!/bin/bash
set +v

########################################################
## Script to Execute Automated testing                ##
##                                                    ##
## Created August 26th, 2011 by B. DUMONT             ##
########################################################

source include


#### Test Cases Execution ####
source cmd_wget "$CRBURL/RunTestCase?ss_ip=$MYIP&ss_p=$MYPORT&browser=$MYBROWSER&Test=Cerberus&TestCase=1000A&Country=RX&Environment=$ENV&Tag=$TAG"
source cmd_wget "$CRBURL/RunTestCase?ss_ip=$MYIP&ss_p=$MYPORT&browser=$MYBROWSER&Test=Cerberus&TestCase=1001A&Country=RX&Environment=$ENV&Tag=$TAG"
source cmd_wget "$CRBURL/RunTestCase?ss_ip=$MYIP&ss_p=$MYPORT&browser=$MYBROWSER&Test=Cerberus&TestCase=1002A&Country=RX&Environment=$ENV&Tag=$TAG"
source cmd_wget "$CRBURL/RunTestCase?ss_ip=$MYIP&ss_p=$MYPORT&browser=$MYBROWSER&Test=Cerberus&TestCase=1003A&Country=RX&Environment=$ENV&Tag=$TAG"
source cmd_wget "$CRBURL/RunTestCase?ss_ip=$MYIP&ss_p=$MYPORT&browser=$MYBROWSER&Test=Cerberus&TestCase=1004A&Country=RX&Environment=$ENV&Tag=$TAG"
source cmd_wget "$CRBURL/RunTestCase?ss_ip=$MYIP&ss_p=$MYPORT&browser=$MYBROWSER&Test=Cerberus&TestCase=1200A&Country=RX&Environment=$ENV&Tag=$TAG"
source cmd_wget "$CRBURL/RunTestCase?ss_ip=$MYIP&ss_p=$MYPORT&browser=$MYBROWSER&Test=Cerberus&TestCase=1201A&Country=RX&Environment=$ENV&Tag=$TAG"
source cmd_wget "$CRBURL/RunTestCase?ss_ip=$MYIP&ss_p=$MYPORT&browser=$MYBROWSER&Test=Cerberus&TestCase=1202A&Country=RX&Environment=$ENV&Tag=$TAG"
source cmd_wget "$CRBURL/RunTestCase?ss_ip=$MYIP&ss_p=$MYPORT&browser=$MYBROWSER&Test=Cerberus&TestCase=1203A&Country=RX&Environment=$ENV&Tag=$TAG"
source cmd_wget "$CRBURL/RunTestCase?ss_ip=$MYIP&ss_p=$MYPORT&browser=$MYBROWSER&Test=Cerberus&TestCase=1204A&Country=RX&Environment=$ENV&Tag=$TAG"
source cmd_wget "$CRBURL/RunTestCase?ss_ip=$MYIP&ss_p=$MYPORT&browser=$MYBROWSER&Test=Cerberus&TestCase=1205A&Country=RX&Environment=$ENV&Tag=$TAG"
source cmd_wget "$CRBURL/RunTestCase?ss_ip=$MYIP&ss_p=$MYPORT&browser=$MYBROWSER&Test=Cerberus&TestCase=1206A&Country=RX&Environment=$ENV&Tag=$TAG"
source cmd_wget "$CRBURL/RunTestCase?ss_ip=$MYIP&ss_p=$MYPORT&browser=$MYBROWSER&Test=Cerberus&TestCase=1207A&Country=RX&Environment=$ENV&Tag=$TAG"
source cmd_wget "$CRBURL/RunTestCase?ss_ip=$MYIP&ss_p=$MYPORT&browser=$MYBROWSER&Test=Cerberus&TestCase=1208A&Country=RX&Environment=$ENV&Tag=$TAG"
source cmd_wget "$CRBURL/RunTestCase?ss_ip=$MYIP&ss_p=$MYPORT&browser=$MYBROWSER&Test=Cerberus&TestCase=1209A&Country=RX&Environment=$ENV&Tag=$TAG"
source cmd_wget "$CRBURL/RunTestCase?ss_ip=$MYIP&ss_p=$MYPORT&browser=$MYBROWSER&Test=Cerberus&TestCase=1210A&Country=RX&Environment=$ENV&Tag=$TAG"
source cmd_wget "$CRBURL/RunTestCase?ss_ip=$MYIP&ss_p=$MYPORT&browser=$MYBROWSER&Test=Cerberus&TestCase=1211A&Country=RX&Environment=$ENV&Tag=$TAG"
source cmd_wget "$CRBURL/RunTestCase?ss_ip=$MYIP&ss_p=$MYPORT&browser=$MYBROWSER&Test=Cerberus&TestCase=1212A&Country=RX&Environment=$ENV&Tag=$TAG"
source cmd_wget "$CRBURL/RunTestCase?ss_ip=$MYIP&ss_p=$MYPORT&browser=$MYBROWSER&Test=Cerberus&TestCase=1213A&Country=RX&Environment=$ENV&Tag=$TAG"
source cmd_wget "$CRBURL/RunTestCase?ss_ip=$MYIP&ss_p=$MYPORT&browser=$MYBROWSER&Test=Cerberus&TestCase=1400A&Country=RX&Environment=$ENV&Tag=$TAG"
source cmd_wget "$CRBURL/RunTestCase?ss_ip=$MYIP&ss_p=$MYPORT&browser=$MYBROWSER&Test=Cerberus&TestCase=1401A&Country=RX&Environment=$ENV&Tag=$TAG"
source cmd_wget "$CRBURL/RunTestCase?ss_ip=$MYIP&ss_p=$MYPORT&browser=$MYBROWSER&Test=Cerberus&TestCase=1402A&Country=RX&Environment=$ENV&Tag=$TAG"
source cmd_wget "$CRBURL/RunTestCase?ss_ip=$MYIP&ss_p=$MYPORT&browser=$MYBROWSER&Test=Cerberus&TestCase=1403A&Country=RX&Environment=$ENV&Tag=$TAG"
source cmd_wget "$CRBURL/RunTestCase?ss_ip=$MYIP&ss_p=$MYPORT&browser=$MYBROWSER&Test=Cerberus&TestCase=1404A&Country=RX&Environment=$ENV&Tag=$TAG"
source cmd_wget "$CRBURL/RunTestCase?ss_ip=$MYIP&ss_p=$MYPORT&browser=$MYBROWSER&Test=Cerberus&TestCase=1405A&Country=RX&Environment=$ENV&Tag=$TAG"
source cmd_wget "$CRBURL/RunTestCase?ss_ip=$MYIP&ss_p=$MYPORT&browser=$MYBROWSER&Test=Cerberus&TestCase=1406A&Country=RX&Environment=$ENV&Tag=$TAG"
source cmd_wget "$CRBURL/RunTestCase?ss_ip=$MYIP&ss_p=$MYPORT&browser=$MYBROWSER&Test=Cerberus&TestCase=1407A&Country=RX&Environment=$ENV&Tag=$TAG"

