/*
 * Cerberus Copyright (C) 2013 - 2017 cerberustesting
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 * This file is part of Cerberus.
 *
 * Cerberus is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Cerberus is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Cerberus.  If not, see <http://www.gnu.org/licenses/>.
 */

var propertyUIList = {
    "fr": [
        {
            "type": "text",
            "value1": "Valeur",
            "value1Class": "col-sm-10",
            "value1EditorMode": "ace/mode/cerberus",
            "value2": null,
            "database": null,
            "length": "[opt] Length",
            "cacheExpire": "[opt] cache Expire (s)",
            "rowLimit": null,
            "nature": "Nature",
            "retry": null,
            "period": null
        },
        {
            "type": "getFromSql",
            "value1": "Requete SQL",
            "value1Class": "col-sm-8",
            "value1EditorMode": "ace/mode/sql",
            "value2": null,
            "database": "Database",
            "length": null,
            "cacheExpire": "[opt] cache Expire (s)",
            "rowLimit": "Row Limit",
            "nature": "Nature",
            "retry": "Number of retry (until non-empty result)",
            "period": "Retry period (ms)"
        },
        {
            "type": "getFromDataLib",
            "value1": "Nom de la DataLib",
            "value1Class": "col-sm-10",
            "value1EditorMode": "ace/mode/cerberus",
            "value2": null,
            "database": null,
            "length": "Length (nb of rows)",
            "cacheExpire": "[opt] cache Expire (s)",
            "rowLimit": "[opt] Row Limit",
            "nature": "Nature",
            "retry": "Number of retry (until non-empty result)",
            "period": "Retry period (ms)"
        },
        {
            "type": "getFromHtml",
            "value1": "Chemin vers l'élément",
            "value1Class": "col-sm-10",
            "value1EditorMode": "ace/mode/xquery",
            "value2": null,
            "database": null,
            "length": null,
            "cacheExpire": "[opt] cache Expire (s)",
            "rowLimit": null,
            "nature": null,
            "retry": null,
            "period": null
        },
        {
            "type": "getFromHtmlVisible",
            "value1": "Chemin vers l'élément",
            "value1Class": "col-sm-10",
            "value1EditorMode": "ace/mode/xquery",
            "value2": null,
            "database": null,
            "length": null,
            "cacheExpire": "[opt] cache Expire (s)",
            "rowLimit": null,
            "nature": null,
            "retry": null,
            "period": null
        },
        {
            "type": "getFromJS",
            "value1": "Commande Javascript",
            "value1Class": "col-sm-10",
            "value1EditorMode": "ace/mode/javascript",
            "value2": null,
            "database": null,
            "length": null,
            "cacheExpire": "[opt] cache Expire (s)",
            "rowLimit": null,
            "nature": null,
            "retry": null,
            "period": null
        },
        {
            "type": "getAttributeFromHtml",
            "value1": "Chemin vers l'élément",
            "value1Class": "col-sm-8",
            "value1EditorMode": "ace/mode/xquery",
            "value2": "Attribute name",
            "database": null,
            "length": null,
            "cacheExpire": "[opt] cache Expire (s)",
            "rowLimit": null,
            "nature": null,
            "retry": null,
            "period": null
        },
        {
            "type": "getFromCookie",
            "value1": "Nom du Cookie",
            "value1Class": "col-sm-8",
            "value1EditorMode": "ace/mode/cerberus",
            "value2": "Cookie attribute",
            "database": null,
            "length": null,
            "cacheExpire": "[opt] cache Expire (s)",
            "rowLimit": null,
            "nature": null,
            "retry": null,
            "period": null
        },
        {
            "type": "getFromXml",
            "value1": "Xpath",
            "value1Class": "col-sm-8",
            "value1EditorMode": "ace/mode/xquery",
            "value2": "[opt] Contenu XML ou URL vers un fichier XML",
            "database": null,
            "length": null,
            "cacheExpire": "[opt] cache Expire (s)",
            "rowLimit": null,
            "nature": null,
            "retry": null,
            "period": null
        },
        {
            "type": "getRawFromXml",
            "value1": "Xpath",
            "value1Class": "col-sm-8",
            "value1EditorMode": "ace/mode/xquery",
            "value2": "[opt] Contenu XML ou URL vers un fichier XML",
            "database": null,
            "length": null,
            "cacheExpire": "[opt] cache Expire (s)",
            "rowLimit": null,
            "nature": null,
            "retry": null,
            "period": null
        },
        {
            "type": "getDifferencesFromXml",
            "value1": "value1",
            "value1Class": "col-sm-8",
            "value1EditorMode": "ace/mode/xquery",
            "value2": "value2",
            "database": null,
            "length": null,
            "cacheExpire": "[opt] cache Expire (s)",
            "rowLimit": null,
            "nature": null,
            "retry": null,
            "period": null
        },
        {
            "type": "getFromJson",
            "value1": "Chemin JSON",
            "value1Class": "col-sm-8",
            "value1EditorMode": "ace/mode/json",
            "value2": "[opt] Contenu JSON ou URL vers un fichier JSON",
            "database": null,
            "length": null,
            "cacheExpire": "[opt] cache Expire (s)",
            "rowLimit": null,
            "nature": null,
            "retry": null,
            "period": null
        },
        {
            "type": "getRawFromJson",
            "value1": "Chemin JSON",
            "value1Class": "col-sm-8",
            "value1EditorMode": "ace/mode/xquery",
            "value2": "[opt] Contenu JSON ou URL vers un fichier JSON",
            "database": null,
            "length": null,
            "cacheExpire": "[opt] cache Expire (s)",
            "rowLimit": null,
            "nature": null,
            "retry": null,
            "period": null
        },
        {
            "type": "getFromNetworkTraffic",
            "value1": "filtre d'URL",
            "value1Class": "col-sm-8",
            "value1EditorMode": "ace/mode/json",
            "value2": "JSON Path",
            "value3": "Activate HTTP response content (Y/N)",
            "database": null,
            "length": null,
            "cacheExpire": "[opt] cache Expire (s)",
            "rowLimit": null,
            "nature": null,
            "retry": null,
            "period": null
        },
        {
            "type": "getFromGroovy",
            "value1": "Groovy command",
            "value1Class": "col-sm-8",
            "value1EditorMode": "ace/mode/groovy",
            "value2": null,
            "database": null,
            "length": null,
            "cacheExpire": "[opt] cache Expire (s)",
            "rowLimit": null,
            "nature": null,
            "retry": null,
            "period": null
        },
        {
            "type": "getFromCommand",
            "value1": "Commande Appium (ex : \"mobile:deviceInfo\")",
            "value1Class": "col-sm-8",
            "value1EditorMode": "ace/mode/shell",
            "value2": "Arguments (ex : {param1: \"val1\", param2: \"val2\"})",
            "database": null,
            "length": null,
            "cacheExpire": "[opt] cache Expire (s)",
            "rowLimit": null,
            "nature": null,
            "retry": null,
            "period": null
        },
        {
            "type": "getElementPosition",
            "value1": "Récupérer la position en Pixel d'un élement (use id=/xpath=/etc syntax - return \"px;py\")",
            "value1Class": "col-sm-8",
            "value1EditorMode": "ace/mode/cerberus",
            "value2": null,
            "database": null,
            "length": null,
            "cacheExpire": "[opt] cache Expire (s)",
            "rowLimit": null,
            "nature": null,
            "retry": null,
            "period": null
        },
        {
            "type": "getOTP",
            "value1": "Récupérer un code OTP à partir d'une valeur de clé",
            "value1Class": "col-sm-8",
            "value1EditorMode": "ace/mode/cerberus",
            "value2": null,
            "database": null,
            "length": null,
            "cacheExpire": "[opt] cache Expire (s)",
            "rowLimit": null,
            "nature": null,
            "retry": null,
            "period": null
        },
        {
            "type": "executeSoapFromLib",
            "value1": "Service lib name",
            "value1Class": "col-sm-8",
            "value1EditorMode": "ace/mode/cerberus",
            "value2": null,
            "database": null,
            "length": null,
            "cacheExpire": "[opt] cache Expire (s)",
            "rowLimit": null,
            "nature": null,
            "retry": null,
            "period": null
        },
        {
            "type": "executeSqlFromLib",
            "value1": "SQL Lib name",
            "value1Class": "col-sm-8",
            "value1EditorMode": "ace/mode/cerberus",
            "value2": null,
            "database": null,
            "length": null,
            "cacheExpire": "[opt] cache Expire (s)",
            "rowLimit": null,
            "nature": null,
            "retry": null,
            "period": null
        }
    ], "en": [
        {
            "type": "text",
            "value1": "Value",
            "value1Class": "col-sm-10",
            "value1EditorMode": "ace/mode/cerberus",
            "value2": null,
            "database": null,
            "length": "[opt] Length",
            "cacheExpire": "[opt] cache Expire (s)",
            "rowLimit": null,
            "nature": "Nature",
            "retry": null,
            "period": null,
            "rank": "Rank"
        },
        {
            "type": "getFromSql",
            "value1": "SQL Query",
            "value1Class": "col-sm-8",
            "value1EditorMode": "ace/mode/sql",
            "value2": null,
            "database": "Database",
            "length": null,
            "cacheExpire": "[opt] cache Expire (s)",
            "rowLimit": "Row Limit",
            "nature": "Nature",
            "retry": "Number of retry (until non-empty result)",
            "period": "Retry period (ms)",
            "rank": "Rank"
        },
        {
            "type": "getFromDataLib",
            "value1": "DataLib name",
            "value1Class": "col-sm-10",
            "value1EditorMode": "ace/mode/cerberus",
            "value2": null,
            "database": null,
            "length": "Length (nb of rows)",
            "cacheExpire": "[opt] cache Expire (s)",
            "rowLimit": "[opt] Row Limit",
            "nature": "Nature",
            "retry": "Number of retry (until non-empty result)",
            "period": "Retry period (ms)",
            "rank": "Rank"
        },
        {
            "type": "getFromHtml",
            "value1": "Element path",
            "value1Class": "col-sm-10",
            "value1EditorMode": "ace/mode/xquery",
            "value2": null,
            "database": null,
            "length": null,
            "cacheExpire": "[opt] cache Expire (s)",
            "rowLimit": null,
            "nature": null,
            "retry": null,
            "period": null,
            "rank": "Rank"
        },
        {
            "type": "getFromHtmlVisible",
            "value1": "Element path",
            "value1Class": "col-sm-10",
            "value1EditorMode": "ace/mode/xquery",
            "value2": null,
            "database": null,
            "length": null,
            "cacheExpire": "[opt] cache Expire (s)",
            "rowLimit": null,
            "nature": null,
            "retry": null,
            "period": null,
            "rank": "Rank"
        },
        {
            "type": "getFromJS",
            "value1": "Javascript command",
            "value1Class": "col-sm-10",
            "value1EditorMode": "ace/mode/javascript",
            "value2": null,
            "database": null,
            "length": null,
            "cacheExpire": "[opt] cache Expire (s)",
            "rowLimit": null,
            "nature": null,
            "retry": null,
            "period": null,
            "rank": "Rank"
        },
        {
            "type": "getAttributeFromHtml",
            "value1": "Element path",
            "value1Class": "col-sm-8",
            "value1EditorMode": "ace/mode/xquery",
            "value2": "Attribute name",
            "database": null,
            "length": null,
            "cacheExpire": "[opt] cache Expire (s)",
            "rowLimit": null,
            "nature": null,
            "retry": null,
            "period": null,
            "rank": "Rank"
        },
        {
            "type": "getFromCookie",
            "value1": "Cookie name",
            "value1Class": "col-sm-8",
            "value1EditorMode": "ace/mode/cerberus",
            "value2": "Cookie attribute",
            "database": null,
            "length": null,
            "cacheExpire": "[opt] cache Expire (s)",
            "rowLimit": null,
            "nature": null,
            "retry": null,
            "period": null,
            "rank": "Rank"
        },
        {
            "type": "getFromXml",
            "value1": "Xpath",
            "value1Class": "col-sm-8",
            "value1EditorMode": "ace/mode/xquery",
            "value2": "[opt] XML or URL to XML file",
            "database": null,
            "length": null,
            "cacheExpire": "[opt] cache Expire (s)",
            "rowLimit": null,
            "nature": null,
            "retry": null,
            "period": null,
            "rank": "Rank"
        },
        {
            "type": "getRawFromXml",
            "value1": "Xpath",
            "value1Class": "col-sm-8",
            "value1EditorMode": "ace/mode/xquery",
            "value2": "[opt] XML or URL to XML file",
            "database": null,
            "length": null,
            "cacheExpire": "[opt] cache Expire (s)",
            "rowLimit": null,
            "nature": null,
            "retry": null,
            "period": null,
            "rank": "Rank"
        },
        {
            "type": "getDifferencesFromXml",
            "value1": "value1",
            "value1Class": "col-sm-8",
            "value1EditorMode": "ace/mode/xquery",
            "value2": "value2",
            "database": null,
            "length": null,
            "cacheExpire": "[opt] cache Expire (s)",
            "rowLimit": null,
            "nature": null,
            "retry": null,
            "period": null,
            "rank": "Rank"
        },
        {
            "type": "getFromJson",
            "value1": "JSON Path",
            "value1Class": "col-sm-8",
            "value1EditorMode": "ace/mode/json",
            "value2": "[opt] JSON or URL to JSON file",
            "database": null,
            "length": null,
            "cacheExpire": "[opt] cache Expire (s)",
            "rowLimit": null,
            "nature": null,
            "retry": null,
            "period": null,
            "rank": "Rank"
        },
        {
            "type": "getRawFromJson",
            "value1": "JSON Path",
            "value1Class": "col-sm-8",
            "value1EditorMode": "ace/mode/json",
            "value2": "[opt] JSON or URL to JSON file",
            "database": null,
            "length": null,
            "cacheExpire": "[opt] cache Expire (s)",
            "rowLimit": null,
            "nature": null,
            "retry": null,
            "period": null,
            "rank": "Rank"
        },
        {
            "type": "getFromNetworkTraffic",
            "value1": "URL filter",
            "value1Class": "col-sm-8",
            "value1EditorMode": "ace/mode/json",
            "value2": "JSON Path",
            "value3": "Activate HTTP response content (Y/N)",
            "database": null,
            "length": null,
            "cacheExpire": "[opt] cache Expire (s)",
            "rowLimit": null,
            "nature": null,
            "retry": null,
            "period": null
        },
        {
            "type": "getFromGroovy",
            "value1": "Groovy command",
            "value1Class": "col-sm-8",
            "value1EditorMode": "ace/mode/groovy",
            "value2": null,
            "database": null,
            "length": null,
            "cacheExpire": "[opt] cache Expire (s)",
            "rowLimit": null,
            "nature": null,
            "retry": null,
            "period": null,
            "rank": "Rank"
        },
        {
            "type": "getFromCommand",
            "value1": "Appium Command (ex : \"mobile:deviceInfo\")",
            "value1Class": "col-sm-8",
            "value1EditorMode": "ace/mode/shell",
            "value2": "Arguments (ex : {param1: \"val1\", param2: \"val2\"})",
            "database": null,
            "length": null,
            "cacheExpire": "[opt] cache Expire (s)",
            "rowLimit": null,
            "nature": null,
            "retry": null,
            "period": null,
            "rank": "Rank"
        },
        {
            "type": "getElementPosition",
            "value1": "Get an element pixel position (use id=/xpath=/etc syntax - return \"px;py\")",
            "value1Class": "col-sm-8",
            "value1EditorMode": "ace/mode/cerberus",
            "value2": null,
            "database": null,
            "length": null,
            "cacheExpire": "[opt] cache Expire (s)",
            "rowLimit": null,
            "nature": null,
            "retry": null,
            "period": null
        },
        {
            "type": "getOTP",
            "value1": "Get an OTP code from a secret key",
            "value1Class": "col-sm-8",
            "value1EditorMode": "ace/mode/cerberus",
            "value2": null,
            "database": null,
            "length": null,
            "cacheExpire": "[opt] cache Expire (s)",
            "rowLimit": null,
            "nature": null,
            "retry": null,
            "period": null
        },
        {
            "type": "executeSoapFromLib",
            "value1": "Service lib name",
            "value1Class": "col-sm-8",
            "value1EditorMode": "ace/mode/cerberus",
            "value2": null,
            "database": null,
            "length": null,
            "cacheExpire": "[opt] cache Expire (s)",
            "rowLimit": null,
            "nature": null,
            "retry": null,
            "period": null,
            "rank": "Rank"
        },
        {
            "type": "executeSqlFromLib",
            "value1": "SQL Lib name",
            "value1Class": "col-sm-8",
            "value1EditorMode": "ace/mode/cerberus",
            "value2": null,
            "database": null,
            "length": null,
            "cacheExpire": "[opt] cache Expire (s)",
            "rowLimit": null,
            "nature": null,
            "retry": null,
            "period": null,
            "rank": "Rank"
        }
    ]
};

